### PR TITLE
Add license check exclusions

### PR DESCRIPTION
**Pull request by ybasket**
Add possibility to exclude certain dependencies from the license check. Use cases are internal dependencies or dependencies for which there's no fitting license category, like the Unicode license before #75.

PS: I know such requests can be annoying, but a release after merging this PR would help me a lot 🙏

### CODE REVIEW

**Comment by mdedetrich** [comment]
This functionality is already supported, see https://github.com/apache/incubator-pekko-http/blob/main/project/LicenseReport.scala#L29-L33

**Comment by ybasket** [comment]
> This functionality is already supported, see https://github.com/apache/incubator-pekko-http/blob/main/project/LicenseReport.scala#L29-L33 as an example?

It is for license reports indeed and that's what inspired this PR which focuses solely on the new `licenseCheck` feature I added in #74. You may want to to not fail the license check for certain dependencies, hence exclude them from the check, but still keep them in the reports – as an example, the use case I had was icu4j with its Unicode license before #75. I don't want to hide it in the report, but I also don't want to fail the check just because there's no license category defined (yet). `licenseDepExclusions` would also remove from the report, so we need something dedicated to the check.

**Comment by mdedetrich** [comment]
> It is for license _reports_ indeed and that's what inspired this PR which focuses solely on the new `licenseCheck` feature I added in #74. You may want to to not fail the license check for certain dependencies, hence exclude them from the check, but still keep them in the reports – as an example, the use case I had was icu4j with its Unicode license before #75. I don't want to hide it in the report, but I also don't want to fail the check just because there's no license category defined (yet). `licenseDepExclusions` would also remove from the report, so we need something dedicated to the check.

Ah I see, I wasn't aware of the new feature that was added. In this case at least from me it looks good, albeit adding a test to sbt scripted would be nice (something equivalent to https://github.com/mdedetrich/sbt-license-report/tree/0f3b261dccea0509bc89d9cf9adcff49089748f6/src/sbt-test/dumpLicenseReport/dep-exclusions-report

**Review by mdedetrich — APPROVED** [review]
Approve from me, but adding a test would be nice.

**Comment by ybasket** [comment]
> Approve from me, but adding a test would be nice.

Tests are a good idea, didn't have them on my radar as I'm a newbie to set plugins. Just added three covering the main cases for `licenseCheck`.

**Review by eed3si9n — APPROVED** [review]
Thanks!

**Pull request merged**
