### PR TITLE
Upgrade to sbt 0.13.11 in order to correctly get info from parent poms

### PR DESCRIPTION
**Pull request by benmccann**
Upgrading SBT fixes https://github.com/sbt/sbt-license-report/issues/7. Also adding a test to prove that it's fixed.

### CODE REVIEW

**Comment by xuwei-k** [comment]
There is a critical issue in sbt 0.13.10-RC1. I think should not use 0.13.10-RC1.
https://github.com/sbt/sbt/issues/2411

**Comment by dwijnand** [comment]
0.13.10-M1 contains the fix for sbt/sbt#2411

**Comment by benmccann** [comment]
Ok, I switched to 0.13.10-M1

**Comment by jsuereth** [comment]
Cool!  I'd like to wait for final before we release though :)

**Comment by benmccann** [comment]
Ok, I split this PR into two parts. Would you guys be able to take a look at https://github.com/sbt/sbt-license-report/issues/16 now and then we can let this part wait?

**Comment by benmccann** [comment]
I've upgraded this PR to use sbt 0.13.11 final now

**Pull request merged**
