### PR TITLE
improve error handling when a url/homepage is invalid

### PR DESCRIPTION
**Pull request by raboof**
Since #134, encountering an 'invalid' URI such as `https://github.com/rnorth/${project.artifactId}` from https://github.com/rnorth/duct-tape would throw an error and fail the entire job. As the user of the plugin likely doesn't have direct influence over the `pom.xml` of the dependencies, it would be better to emit a warning. With this change, it becomes:

```
sbt-license-report: dependency [org.rnorth.duct-tape:duct-tape:1.0.8] has malformed homepage url [https://github.com/rnorth/${project.artifactId}]
```

This improves the situation described in #144.

I'm not sure it is a full fix, because I'm not sure `https://github.com/rnorth/${project.artifactId}` is actually invalid here: I haven't checked whether maven placeholders are allowed here, and if so, whose responsibility it is to make sure they get resolved (see #92 for that aspect).

### CODE REVIEW

**Review by mdedetrich — APPROVED** [review]
Lgtm

**Comment by raboof** [comment]
would be great to get this merged ;)

**Review by eed3si9n — APPROVED** [review]

**Comment by eed3si9n** [comment]
Merged 😃

**Comment by akreit** [comment]
@eed3si9n any plans on putting this into a release soon?

**Comment by mdedetrich** [comment]
I believe I also have permissions to trigger a release, will do so if @eed3si9n doesn't respond within a week (ping me if I forget)

**Comment by eed3si9n** [comment]
@mdedetrich Feel free to release today.

**Comment by Spezialissimo** [comment]
Hi @mdedetrich,
It seems this fix hasn't been released yet — if you're able to do it, that would be much appreciated!

Also, I noticed that this change addresses cases where the pom.txt contains a variable in the URL, which Ivy doesn't resolve, leading to a URISyntaxException:

```scala
try {
  Some(new URI(string).toURL)
} catch {
  case _: URISyntaxException =>
    log.warn(s"sbt-license-report: dependency [${dep.module}] has malformed homepage url [$string]")
    None
}
```

Would it be possible to manually substitute the variable values before parsing the URL?
If you're short on time, I’d be happy to look into this and open a PR.

**Comment by lancewalton** [comment]
No need to apologise. I could easily have published a local copy :-)

Thank you. You are awesome.

**Pull request merged**
