### PR TITLE
Add link to the homepage of the dependency

### PR DESCRIPTION
**Pull request by kbedel**
Implements #31. This is just a rebased version of PR #32

### CODE REVIEW

**Comment by lightbend-cla-validator** [comment]
Hi @kbedel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by lightbend-cla-validator** [comment]
Hi @kbedel,

Thank you for your contribution! We really value the time you've taken to put this together.

Before we proceed with reviewing this pull request, please sign the Lightbend Contributors License Agreement:

[http://www.lightbend.com/contribute/cla](http://www.lightbend.com/contribute/cla)

**Comment by kbedel** [comment]
My employer has now signed the Corporate CLA

**Comment by jeffrey-aguilera** [comment]
Any reason this isn't being merged?

**Comment by eed3si9n** [comment]
It slipped through our attention.

**Pull request merged**
