### PR TITLE
Fixes #10 - License report includes evicted modules.

### LINKED ISSUE #10: Evicted libraries incorrectly included in report
I'm seeing lots of duplicate libraries in my report. E.g.

>none specified 	 	com.google.http-client # google-http-client # 1.19.0
none specified 	 	com.google.http-client # google-http-client # 1.20.0 

It doesn't seem necessary to included evicted libraries in the license report since they're not actually being used. In this case we could just include 1.20.0

### PR DESCRIPTION
**Pull request by jsuereth**
Fixes #10 

* Add a quick filter for evicted modules.
* Fix source compatibility issues with the plugin.

cc> @benmccann review by @eed3si9n

### CODE REVIEW

**Comment by eed3si9n** [comment]
LGTM. There's also `isBlacklisted` that you might be interested in.

**Comment by eed3si9n** [comment]
Is there a test that confirms that it fixes #10?

**Comment by jsuereth** [comment]
Not yet, working on that now.

**Comment by jsuereth** [comment]
@eed3si9n Ok, test is complete.

**Comment by eed3si9n** [comment]
Could you also configure Travis? It's two lines - https://github.com/sbt/sbt-buildinfo/blob/master/.travis.yml

**Comment by jsuereth** [comment]
@eed3si9n done.

**Comment by eed3si9n** [comment]
Merged.

**Comment by benmccann** [comment]
Awesome. Thank you guys!

**Pull request merged**
